include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/imputation.smk"
include: "rules/normalization.smk"
include: "rules/residuals.smk"
include: "rules/feature_selection.smk"


rule feature_selection_workflow:
    input:
        expand("tables/pca/selected_{selected}_{cv_selected}.tsv", selected=[0,125], cv_selected=[0,1250])
