[project]
name = "metabolomics-base-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "metabotk>=0.3.2",
    "pandas>=2.2.3",
    "snakemake>=8.27.1",
]
